import matter from 'gray-matter';
import { marked } from 'marked';
import { readdir, readFile, writeFile } from 'fs/promises';
import { join, basename } from 'path';

interface Product {
  id: string;
  title: string;
  taglineZh: string | null;
  votes: number;
  url: string | null;
  website: string | null;
  date: string;
  topicsZh: string;
  isAi: boolean;
  thumbnail: string | null;
  descriptionHtml: string | null;
  slug: string;
}

interface ImageMetadata {
  localPath: string;
  r2Key: string;
}

async function parseProduct(productDir: string): Promise<Product> {
  const indexPath = join(productDir, 'index.md');
  const zhPath = join(productDir, 'zh.md');

  const indexContent = await readFile(indexPath, 'utf-8');
  const zhContent = await readFile(zhPath, 'utf-8');

  const { data: frontmatter } = matter(indexContent);

  const taglineMatch = zhContent.match(/^> (.+)$/m);
  const taglineZh = taglineMatch ? taglineMatch[1] : frontmatter.tagline;

  const descriptionMatch = zhContent.match(/## 产品简介\n([\s\S]+?)(?:## |$)/);
  const descriptionText = descriptionMatch ? descriptionMatch[1].trim() : '';
  const descriptionHtml = await marked.parse(descriptionText);

  const topics = frontmatter.topics || [];
  const topicsZh = JSON.stringify(topics);

  const imagesDir = join(productDir, 'images');
  const imageFiles = await readdir(imagesDir).catch(() => []);
  const thumbnailFile = imageFiles.find((f) => f.startsWith('thumb'));
  const thumbnail = thumbnailFile ? `images/${basename(productDir)}/${thumbnailFile}` : null;

  return {
    id: frontmatter.id,
    title: frontmatter.title,
    taglineZh,
    votes: frontmatter.votes || 0,
    url: frontmatter.url,
    website: frontmatter.website,
    date: frontmatter.date,
    topicsZh,
    isAi: frontmatter.is_ai || false,
    thumbnail,
    descriptionHtml,
    slug: '',
  };
}

function escapeSql(str: string | null): string {
  if (str === null) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

function generateSql(date: string, products: Product[]): string {
  const values = products.map((p, index) => {
    const rank = index + 1;
    return `(${escapeSql(p.id)}, ${escapeSql(date)}, ${rank}, ${escapeSql(p.slug)}, ${escapeSql(p.title)}, ${escapeSql(p.taglineZh)}, ${p.votes}, ${escapeSql(p.url)}, ${escapeSql(p.website)}, ${escapeSql(p.topicsZh)}, ${p.isAi ? 1 : 0}, ${escapeSql(p.thumbnail)}, ${escapeSql(p.descriptionHtml)})`;
  }).join(',\n');

  return `
-- Product Hunt Upload SQL for ${date}
-- Generated by prepare.ts

INSERT OR REPLACE INTO ph_products (id, date, rank, slug, title, tagline_zh, votes, url, website, topics_zh, is_ai, thumbnail, description_html)
VALUES
${values};

INSERT OR REPLACE INTO ph_dates (date, source, product_count, created_at)
VALUES (${escapeSql(date)}, 'producthunt', ${products.length}, CURRENT_TIMESTAMP);
  `.trim();
}

async function main() {
  const ARGS = process.argv.slice(2);
  const DATE_ARG = ARGS.find((arg) => arg.startsWith('--date='));

  if (!DATE_ARG) {
    console.error('Usage: npx tsx scripts/prepare.ts --date=YYYY-MM-DD');
    process.exit(1);
  }

  const DATE = DATE_ARG.split('=')[1];
  const INPUT_DIR = join(process.cwd(), '../../follow/output/producthunt-daily', DATE);

  console.log('\n🏗️  Preparing Data...');
  console.log(`   Date: ${DATE}`);
  console.log(`   Input: ${INPUT_DIR}`);

  const productDirs = await (await readdir(INPUT_DIR, { withFileTypes: true }))
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  console.log(`   Found ${productDirs.length} products`);

  const products: Product[] = [];
  const images: ImageMetadata[] = [];

  for (const slug of productDirs) {
    const productDir = join(INPUT_DIR, slug);
    try {
      const product = await parseProduct(productDir);
      product.slug = slug;
      products.push(product);

      const imagesDir = join(productDir, 'images');
      const imageFiles = await readdir(imagesDir).catch(() => []);
      for (const file of imageFiles) {
        images.push({
          localPath: join(imagesDir, file),
          r2Key: `producthunt/${DATE}/images/${slug}/${file}`
        });
      }
    } catch (e) {
      console.error(`   ❌ Failed to parse ${slug}: ${(e as Error).message}`);
    }
  }

  // Write SQL
  const sql = generateSql(DATE, products);
  const sqlPath = join(process.cwd(), `upload-${DATE}.sql`);
  await writeFile(sqlPath, sql);
  console.log(`\n   ✓ SQL generated: ${sqlPath}`);

  // Write Manifest
  const manifestPath = join(process.cwd(), `images-${DATE}.json`);
  await writeFile(manifestPath, JSON.stringify(images, null, 2));
  console.log(`   ✓ Image manifest generated: ${manifestPath}`);

  console.log('\n✨ Preparation complete!\n');
}

main().catch(console.error);
